name: Build for multiple platforms

on:
  push:
    paths:
      - '**.c'
      - '**.h'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      # - name: Install Xcode Command Line Tools
      #   if: runner.os == 'macOS'
      #   run: xcode-select --install
        
      # - name: Install dependencies (Linux)
      #   if: runner.os == 'Linux'
      #   run: sudo apt-get update && sudo apt-get install -y gcc
        
      # - name: Install dependencies (Windows)
      #   if: runner.os == 'Windows'
      #   run: choco install mingw -y
        
      - name: Build for Linux/macOS
        if: runner.os != 'Windows'
        run: gcc aimerge.c -o aim-${{ runner.os }}
        
      - name: Build for Windows
        if: runner.os == 'Windows'
        run: gcc aimerge.c -o aim.exe
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aimerge-${{ runner.os }}
          path: aimerge-${{ runner.os }}*
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aimerge-${{ runner.os }}*
          asset_name: aimerge-${{ runner.os }}
          asset_content_type: application/octet-stream
